### ISSUE TITLE
File corrupt and missing .sh component

### ISSUE THREAD

**Issue by bmakii** [cselab/TScratch#4]
Hi there,
I tried downloading the Mac version and when I try to open the TScratch_noMCR_pkg .zip file, the product that appears says that it cannot open because it's not in the correct format or the file is corrupt. Additionally, I tried looking in the INSTALL file and there was a link to CSE that for a 'simple' download that now says the page is not found. I went ahead and downloaded the master.zip file hoping that maybe something was hiding in there and found a lot of scripts for the runtime program...however the main file needed "run_TScratch.sh" is still nowhere to be found which has been brought up in previous issues. If this is located in the TScratch_noMCR_pkg.zip file then something within that file is corrupt and cannot be accessed.

Regards

**Comment by phadjido** [comment]
The download links have been updated.
